Update resources.sh to support submitting missing resources YAML
This patch add in resources.sh another command: add_missing_resources
that calls the managesf endpoint in order to get resources
that exist on the services but not in the config repository.

A YAML file is fetched from the managesf endpoint and if the "submit"
argument is provided a review is submitted.
This review contains a special tag in its commit message
"sf-resources: skip-apply" to tell "resources.sh apply"
to avoid calling the apply endpoint of managesf. Indeed
we just want to re-sync the config repo and nothing have to
be applied.

This feature will be used to boostrap that config/resources/
tree from an already existing SF platform. Or can be also
used when resources has been created on the services by
bypassing the config resources GIT style workflow.

A functional test is added along this patch.

Depends-on: I003acea6459e661f5ae40925a9b8f64b51d0d00b
Change-Id: I01fae160314da1dfae0a464c361f56731588d874

diff --git a/config/ansible/roles/sf-jenkins/templates/resources.sh.j2 b/config/ansible/roles/sf-jenkins/templates/resources.sh.j2
--- a/config/ansible/roles/sf-jenkins/templates/resources.sh.j2
+++ b/config/ansible/roles/sf-jenkins/templates/resources.sh.j2
@@ -8,6 +8,7 @@ set -e
 ### resources get/post/put will be called through the
 ### sf-config-update mechanism
 
+FQDN="{{ fqdn }}"
 GATEWAY_URL="{{ gateway_url }}"
 ENDPOINT="$GATEWAY_URL/manage/resources/"
 SPASS={{ creds_sf_service_user_pwd }}
@@ -19,7 +20,7 @@ VALIDATED_OUTPUT="validated-output"
 trap "rm -f $COOKIE_PATH && rm -f $VALIDATED_OUTPUT && rm -f $APPLIED_OUTPUT" EXIT
 
 [ -z "$1" ] && {
-    echo "Valid arguments are validate, apply, direct_apply, get. Exit."
+    echo "Valid arguments are validate, apply, direct_apply, get, get_missing_resources. Exit."
     exit 1
 }
 
@@ -62,9 +63,33 @@ case $1 in
             echo "Resource modifications validation failed (API return code: $http_code)."
             exit 1
         }
+        [ -d "$WORKSPACE/config/.git" ] && {
+            cd $WORKSPACE/config
+            git log -1 --no-merges
+            if git log -1 --no-merges | grep "sf-resources: skip-apply" > /dev/null; then
+                echo
+                echo "The commit msg tag: 'sf-resources: skip-apply' has been detected."
+                echo "The approval of this patch won't trigger the creation of the resources above."
+                echo "The purpose of this commit is usually to re-sync config/resources with the reality."
+            fi
+        } || {
+            echo "Script ran outside of a job workspace."
+        }
         exit 0
         ;;
     apply)
+        clone=$(mktemp -d)
+        git clone $GATEWAY_URL/r/config $clone
+        cd $clone
+        if git log -1 --no-merges | grep "sf-resources: skip-apply" > /dev/null; then
+            echo
+            echo "The commit msg tag: 'sf-resources: skip-apply' has been detected."
+            echo "Skip resources apply."
+            rm -R $clone
+            exit 0
+        fi
+        cd -
+        rm -R $clone
         http_code=$(curl -s -w "%{http_code}" -b $COOKIE_PATH \
          -X PUT $ENDPOINT -o $APPLIED_OUTPUT)
         cat $APPLIED_OUTPUT | python -m json.tool
@@ -88,6 +113,56 @@ case $1 in
         ;;
     get)
         curl -s -b $COOKIE_PATH $ENDPOINT | python -m json.tool
+        ;;
+    get_missing_resources)
+        curl -s -b $COOKIE_PATH "$ENDPOINT?get_missing_resources=true" -o missing_resources.json
+        python <<SCRIPT
+import json
+import yaml
+
+# Be sure multiline are pretty represented
+def str_presenter(dumper, data):
+  if len(data.splitlines()) > 1:  # check for multiline string
+    return dumper.represent_scalar('tag:yaml.org,2002:str', data, style='|')
+  return dumper.represent_scalar('tag:yaml.org,2002:str', data)
+
+yaml.add_representer(unicode, str_presenter)
+yaml.add_representer(str, str_presenter)
+data = json.load(file('missing_resources.json'))
+s = yaml.dump(data[1], default_flow_style=False)
+file('missing_resources.yaml', 'w').write(s)
+if data[0]:
+    print "It appears some issues occured during data fetching:"
+for log in data[0]:
+    print log
+    print "---"
+print "YAML file to submit as a review to the config repo is : missing_resources.yaml"
+SCRIPT
+        [ "$2" == "submit" ] && {
+            clone=$(mktemp -d)
+            msg=$(mktemp)
+            git clone git+ssh://$FQDN/config $clone
+            cp missing_resources.yaml $clone/resources/missing_resources_$(date +%s).yaml
+            cat > $msg << EOF
+Propose missing resources to the config repo
+
+This change should be approved as it is then
+once merged fell free to re-organize as you want.
+
+sf-resources: skip-apply
+EOF
+            (
+                cd $clone
+                git add -A
+                git commit -F $msg
+                git review
+            )
+            rm -R $clone
+            rm $msg
+        } || {
+            echo "You can automatically propose the file as review by running:"
+            echo "$(basename $0) get_missing_resources submit"
+        }
         ;;
     *)
         echo "Action not supported."
